### ISSUE TITLE
Peers don't deploy on latest version

### ISSUE THREAD

**Issue by chrisalexandrepena** [SubstraFoundation/hlf-k8s#101]
I'm trying to run hlf-k8s using the latest line on the compatibility table. I'm running Ubuntu Server 18.05.4, with the following software versions:

- minikube `1.9.2`
- docker `19.03.13`
- kubernetes `1.15.11`
- hlf-k8s `0.0.13`
- substra-chaincode `0.0.11`
- skaffold `1.8.0`
- helm `3.4.1`
- kubectl `1.18.0`

I've tried using a local (by removing the `chaincode[0].src` entry in the `skaffold.yaml` file, and setting `chaincodes[0].hostPath` to the absolute path to the chaincode repository) and a remote (by setting `chaincode[0].src` to `https://github.com/SubstraFoundation/substra-chaincode/archive/0.0.11.tar.gz` in the `skaffold.yaml` file) version of the chaincode repository.
I've changed the hlf-k8s chart's `requirements.yaml` file to replace `https://kubernetes-charts.storage.googleapis.com` with `https://charts.helm.sh/stable`, and then ran a

```
helm dependency update $absolute_path_to_chart
```

I then run the `skaffold run` command and here's the error I get from the `org-1/network-org-1-peer-1-hlf-peer` pod:

```
[endorser] callChaincode -> INFO 223 [yourchannel][4ba51601] Entry chaincode: name:"lscc"
[lscc] executeDeployOrUpgrade -> ERRO 224 cannot get package for chaincode (mycc:1.0)-err:open /var/hyperledger/production/chaincodes/mycc.1.0: no such file or directory
[endorser] callChaincode -> INFO 225 [yourchannel][4ba51601] Exit chaincode: name:"lscc"  (1ms)
[endorser] ProcessProposal -> ERRO 226 [yourchannel][4ba51601] simulateProposal() resulted in chaincode name:"lscc"  response status 500 for txid: 4ba516018a438e897a69671558f35ea65f6fa339ee943a7eee0ed930458325fe
[comm.grpc.server] 1 -> INFO 227 unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.peer_address=172.17.0.26:42370 grpc.peer_subject="CN=user,OU=peer,O=Hyperledger,ST=North Carolina,C=US" grpc.code=OK grpc.call_duration=1.501797ms
```

**Comment by natct10** [comment]
I have to say that I am facing the same issues, with the same setup and versions, and the pod `network-orderer-hlf-ord` from the orderer namespace is starting but showing numerous grpc errors, like:
```sh
│ 2020-11-18 12:53:06.674 UTC [common.deliver] Handle -> WARN 30a Error reading from 172.17.0.11:50710:  │
│ rpc error: code = Canceled desc = context canceled                                                     │
│ 2020-11-18 12:53:06.674 UTC [comm.grpc.server] 1 -> INFO 30b streaming call completed grpc.service=ord │
│ erer.AtomicBroadcast grpc.method=Deliver grpc.peer_address=172.17.0.11:50710 grpc.peer_subject="CN=use │
│ r,OU=orderer,O=Hyperledger,ST=North Carolina,C=US" error="rpc error: code = Canceled desc = context ca │
│ nceled" grpc.code=Canceled grpc.call_duration=13.446338ms 
```
Do you have any suggestion for investigating this further?

**Comment by chrisalexandrepena** [comment]
Also, I'm running minikube with "none" drivers
