### ISSUE TITLE
Warn user if persistence is disabled

### ISSUE THREAD

**Issue by Kelvin-M** [SubstraFoundation/hlf-k8s#118]
With https://helm.sh/docs/topics/charts/#schema-files, we need to warn user if they deploy hlf-k8s without persistence over peer, orderer, ca, couchdb !

**Comment by Kelvin-M** [comment]
It seems to be complicated to do so with json schema.
We can alternatively switch persistence true by default like bitnami charts like https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq. What do you think ?

**Comment by inalgnu** [comment]
@Kelvin-M I think it's more safe to enable it by default. So 👍 for me.
