### ISSUE TITLE
Is it possible to add a new org to an existing network?

### ISSUE THREAD

**Issue by sivaramsk** [SubstraFoundation/hlf-k8s#89]
Is it possible to add new org to an already deployed network?

**Comment by Kelvin-M** [comment]
Yes, it's the aim of the app-channel operator. Depending on how you deploy your network and which policy is defined for your channel.
You need to add the new org configuration an existing org to add it if case of ANY policy, a majority of existing org in case of MAJORITY policy.
For instance, in a MAJORITY policy setup, you can use skaffold build + run with https://github.com/SubstraFoundation/hlf-k8s/tree/master/examples/3-orgs-policy-majority to deploy 3 orgs, and then skaffold run with https://github.com/SubstraFoundation/hlf-k8s/tree/master/examples/4-orgs-policy-majority without deleting anything, it will add a new org (4) to the existing orgs (1,2,3). You should update the sequence value (from 1. to 2.) for that which will be possible when #103 will be merge. 

It will update the values and, consequently, the app-channel operators of the 3 orgs to add the 4th org to the channel.
